### ISSUE TITLE
Saved Searches are called "Saved Saved Searches" in the System Setting tab

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/disco-data-pkg#9]
The word "saved" is duplicated in the Saved Searches card title.

![Screen Shot 2018-04-30 at 2.43.39 PM.png](https://images.zenhubusercontent.com/5ae784c04b5806bc2bd13b56/b6d57b94-2450-4a0d-a518-0e87065ab27a)

**Comment by chiatt** [comment]
No longer an issue in the new resource editor
